version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo ZAPPA_DEPLOY_CLI = $ZAPPA_DEPLOY_CLI
      - $ZAPPA_DEPLOY_CLI