version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      # ----- グローバル(ルート)Python環境 -----
      # pip を最新にする
      - python -m pip install --upgrade pip
      #  -----Python仮想環境 -----
      # 仮想環境作成
      - python -m venv venv
      # 有効化
      - . venv/bin/activate
      # パッケージインストール
      - pip install -r requirements.txt
      # Pythonバージョン確認
      - python -V
  build:
    commands:
      - echo ZAPPA_DEPLOY_CLI = $ZAPPA_DEPLOY_CLI
      - $ZAPPA_DEPLOY_CLI