version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      # -----Python仮想環境 -----
      # 仮想環境作成
      - python -m venv venv
      # 有効化
      - . venv/bin/activate
      # pip を最新にする
      - pip install --upgrade pip
      # パッケージインストール
      - pip install -r requirements.txt
      # Pythonバージョン確認
      - python -V
  build:
    commands:
      - aws lambda list-functions
      # https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/gettingstarted-awscli.html#with-userapp-walkthrough-custom-events-list-functions
      # https://jmespath.org/specification.html#equality-operators
      - functionName = $(aws lambda list-functions 
          --region ap-northeast-1
          --query 'Functions[?FunctionName==`app-flask-cicd-test-dev`].FunctionName'
          --output text)
      # https://dev.classmethod.jp/articles/multiple-line-command-and-conditional-statements-on-codebuild-buildspec-yml/
      # https://qiita.com/egawa_kun/items/196cd354c0d8e4e0fefc
      - |
        if [ $functionName = "app-flask-cicd-test-dev" ]; then
          zappa update dev
        else
          zappa deploy dev
        fi

#      - echo ZAPPA_DEPLOY_CLI = $ZAPPA_DEPLOY_CLI
#      - $ZAPPA_DEPLOY_CLI