version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - python -m venv zappabuild
      - source zappabuild/bin/activate
      - pip install -r requirements.txt
      - python -V
  build:
    commands:
      - $ZAPPA_DEPLOY_CLI